### ISSUE TITLE
Shared photos to go into a default album created for each user when the first photo is shared

### ISSUE THREAD

**Issue by isoguci1** [hypeJunction/hypeWall#55] opened 2015-01-11 23:17 UTC
Currently the photos saved as photos. This creates some discrepancy, as usually photos are organized into (Tidypics) albums. So when you look at a user's photo's, the ones shared via hypeWall are missing there. 

I believe the following behaviour would be more consistent across elgg:
- When user shares a photo via hypeWall, it is saved in the default (or "generic") album of the user. The first time a user shares a photo via hypeWall, the default album is automatically created. As for albums, I mean the tidypics albums. And they are per user (as opposed to site-wide).
regards.

**Comment by isoguci1** [comment] 2015-01-11 23:37
CORRECTİON: "Currently the photos saved as photos" should read as: "Currently the photos saved as FILES".

**Comment by hypeJunction** [comment] 2015-07-27 21:51
Dupe of #18

**Closed by hypeJunction** 2015-07-27 21:51 UTC
